"""Initial migration

Revision ID: bd2d4f6553b3
Revises: 
Create Date: 2024-12-15 20:39:06.769235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2d4f6553b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('climate', sa.String(length=50), nullable=True),
    sa.Column('best_time_to_visit', sa.String(length=100), nullable=True),
    sa.Column('budget_category', sa.String(length=20), nullable=True),
    sa.Column('activities', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.String(length=20), nullable=True),
    sa.Column('travel_style', sa.String(length=50), nullable=True),
    sa.Column('preferred_activities', sa.String(length=200), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('international_domestic', sa.String(length=20), nullable=True),
    sa.Column('time_of_trip', sa.String(length=50), nullable=True),
    sa.Column('date_range', sa.String(length=50), nullable=True),
    sa.Column('demographic', sa.String(length=200), nullable=True),
    sa.Column('scenic_or_activities', sa.String(length=50), nullable=True),
    sa.Column('nightlife', sa.Boolean(), nullable=True),
    sa.Column('itinerary_planner', sa.String(length=100), nullable=True),
    sa.Column('currency_exchange', sa.String(length=50), nullable=True),
    sa.Column('hotels', sa.String(length=100), nullable=True),
    sa.Column('guides', sa.String(length=50), nullable=True),
    sa.Column('road_trips', sa.Boolean(), nullable=True),
    sa.Column('flights', sa.String(length=100), nullable=True),
    sa.Column('night_out', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    op.drop_table('user')
    op.drop_table('destination')
    # ### end Alembic commands ###
